FIRST_NAME_LOCATOR = "id=firstname"
LAST_NAME_LOCATOR = "id=lastname"
BIRTH_DATE_LOCATOR = "id=birthdate"
GENDER_MALE_LOCATOR = "*css=label >> id=gendermale"
STREET_ADDRESS_LOCATOR = "id=streetaddress"
COUNTRY_LOCATOR = "id=country"
ZIP_CODE_LOCATOR = "id=zipcode"
CITY_LOCATOR = "id=city"
OCCUPATION_LOCATOR = "id=occupation"
HOBBY_CLIFF_DIVING = "text=Cliff Diving"
NEXT_PRODUCT_DATA = "id=nextenterproductdata"
