FIRST_NAME = "id=firstname"
LAST_NAME = "id=lastname"
BIRTH_DATE = "id=birthdate"
GENDER_MALE = "*css=label >> id=gendermale"
STREET_ADDRESS = "id=streetaddress"
COUNTRY = "id=country"
ZIP_CODE = "id=zipcode"
CITY = "id=city"
OCCUPATION = "id=occupation"
HOBBY_CLIFF_DIVING = "text=Cliff Diving"
NEXT_PRODUCT_DATA = "id=nextenterproductdata"
