START_DATE_LOCATOR = "id=startdate"
INSURANCE_SUM_LOCATOR = "id=insurancesum"
MERIT_RATING_LOCATOR = "id=meritrating"
DAMAGE_INSURANCE_LOCATOR = "id=damageinsurance"
EURO_PROTECTION = "*css=label >> id=EuroProtection"
COURTESY_CAR_LOCATOR = "id=courtesycar"
NEXT_PRICE_OPTION = "id=nextselectpriceoption"
